<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_cat_title = $_helper->categoryAttribute($_category, $_category->getName(), 'name');
?>

<div class="category-header">
    <div class="category-image-wrap">
        <span class="category-minititle"><?php echo $_cat_title ?></span>
        <?php if($_imgUrl = $_category->getImageUrl()): ?>
            <?php echo $_helper->categoryAttribute($_category, "<p class='category-image'><img src=" . $_imgUrl . "></p>", 'image') ?>
        <?php endif; ?>
    </div>
    <div class="category-title-wrap">
        <h1><?php echo $_cat_title ?></h1>
    </div>
</div>

<div class="clear"></div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
