<div class="eyewear-couponletter-wrap">
	<div class="eyewear-couponletter">
		<div class="couponletter-left">
			<img src="<?php echo $this->getSkinUrl('images/coupon.jpg') ?>">
		</div>
		<div class="couponletter-right">
			<div class="eyewear-couponletter-inner">
				<h3><?php echo $this->__('Get your coupons!') ?></h3>
				<p><?php echo $this->__('We say no to spam-looking email lists that no one wants to read. We offer only individual couponsletters, which allows us to give our customers the biggest discount possible.') ?></p>
				<div class="email-input-wrap">
				  <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
					<input type="text" name="email" id="newsletter" class="required-entry validate-email" />
					<button type="submit" class="ez-btn"><?php echo $this->__('Sign Up') ?></button>
				  </form>
				  <script type="text/javascript">
			      //<![CDATA[
			        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
			      //]]>
			      </script>
				</div>
			</div>
		</div>
	</div>
</div>
