<div class="eyewear-sides-wrap">
	<div class="eyewear-sides">
		<div class="eyeglasses">
			<div class="eyewear-sides-inner">
				<h2><?php echo $this->__('EYEGLASSES') ?></h2>
				<a class="ez-btn" href="<?php echo $this->getUrl('eyeglasses') ?>"><?php echo $this->__('Shop Now') ?></a>
			</div>
		</div>
		<div class="sunglasses">
			<div class="eyewear-sides-inner">
				<h2><?php echo $this->__('SUNGLASSES') ?></h2>
				<a class="ez-btn" href="<?php echo $this->getUrl('sunglasses') ?>"><?php echo $this->__('Shop Now') ?></a>
			</div>
		</div>
	</div>
</div>