
<div class="eyewear-sides-wrap">
	<div class="eyewear-side eyeglasses-side">
		<img src="<?php echo $this->getSkinUrl('images/eyewear-eyeglasses.jpg') ?>">
		<div class="eyewear-sides-inner">
			<h2><?php echo $this->__('EYEGLASSES') ?></h2>
			<a class="dark-btn" href="<?php echo $this->getUrl('eyeglasses') ?>"><?php echo $this->__('Shop Now') ?></a>
		</div>
	</div>
	<div class="eyewear-side sunglasses-side">
		<img src="<?php echo $this->getSkinUrl('images/eyewear-sunglasses.jpg') ?>">
		<div class="eyewear-sides-inner">
			<h2><?php echo $this->__('SUNGLASSES') ?></h2>
			<a class="dark-btn" href="<?php echo $this->getUrl('sunglasses') ?>"><?php echo $this->__('Shop Now') ?></a>
		</div>
	</div>
</div>