<div class="eyewear-instagram-wrap">
	<div class="eyewear-instagram">
		<div class="instagram-title">@EASYOPTIX</div>
		<div class="instagram-cols">
			<div class="instagram-col">
				<img src="<?php echo $this->getSkinUrl('images/insta-easyoptix/1.jpg') ?>">
			</div>
			<div class="instagram-col">
				<img src="<?php echo $this->getSkinUrl('images/insta-easyoptix/2.jpg') ?>">
			</div>
			<div class="instagram-col">
				<img src="<?php echo $this->getSkinUrl('images/insta-easyoptix/3.jpg') ?>">
			</div>
		</div>
	</div>
	<div class="block-section-separator"></div>
</div>