
<?php $specials = $this->special_cats;
      $cats = $this->cats;
?>
<div class="nav-container">
  <div class="nav-container-inner">
    <ul id="nav">
      <?php foreach ($cats as $c) : ?>
        <li class="level0 parent" data-id="<?php echo $c['id'] ?>">
          <a href="<?php echo $c['url'] ?>"><?php echo $c['name'] ?></a>
          <span><?php echo $c['name'] ?></span>
        </li>
      <?php endforeach ?>
    </ul>
    <ul id="inner-nav">
      <?php $i=0; foreach ($cats as $c) : ?>
        <?php $name = $c['name']; if ($name=='Men' || $name=='Women') : ?>
          <ul class="level0 child child-cols cat-<?php echo $c['id'] ?>">
            <li class="child-col">
              <span><?php echo $name . "'s Department" ?></span>
              <ul>
                <?php foreach ($c['children'] as $child) :?>
                  <?php if ($child['name'] == 'Sale') : ?>
                    </ul>
                    <br>
                    <span><?php echo $name . "'s " . $child['name'] ?></span>
                    <ul>
                      <li class="col1">
                        <a href="<?php echo $child['url'] ?>">
                          <span><?php echo $child['name'] ?></span>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <?php elseif ($child['name'] == 'Styles' || $child['name'] == 'Brands') : ?>
                    <li class="child-col">
                      <span><?php echo $name . "'s " . $child['name'] ?></span>
                      <ul>
                        <?php foreach ($child['children'] as $child2) : ?>
                        <li class="col1">
                          <a href="<?php echo $child2['url'] ?>">
                            <span><?php echo $child2['name'] ?></span>
                          </a>
                        </li>
                        <?php endforeach ?>
                      </ul>
                    </li>
                  <?php else : ?>
                    <li class="col1">
                      <a href="<?php echo $child['url'] ?>">
                        <span><?php echo $child['name'] ?></span>
                      </a>
                    </li>
                <?php endif ?>          
              <?php endforeach ?>
              <li class="child-col minibanner-wrap">
                <?php $special = $specials[$name] ?>
                      <a title="<?php echo $special['name'] ?>" href="<?php echo $this->getUrl($special['url']) ?>">
                        <img alt="<?php echo $special['name'] ?>" src="<?php echo $this->getSkinUrl($special['image']) ?>">   
                      </a>
                  </li>
          </ul>
        <?php elseif ($name=='Brands' || $name=='Styles') : ?>
          <ul class="level0 child child3 <?php echo $name . ' cat-' . $c['id']; ?>">
            <?php foreach($c['children'] as $child2) : ?>
            <li class="level1">
              <a title="<?php echo $child2['name'] ?>" href="<?php echo $child2['url'] ?>">
                <?php $image = strtolower('images/media/' . $name . '/' . str_replace(" ", "-", $child2['name']) . '.jpg') ?>
                <img src="<?php echo $this->getSkinUrl($image) ?>"> 
                <?php if ($name == 'Styles') echo "<span>" . $child2['name'] . "</span>"; ?> 
              </a>
            </li>
            <?php endforeach ?>
          </ul>
        <?php else : ?>
          <ul class="level0 child child5 cat-<?php echo $c['id'] ?>">
            <?php foreach($c['children'] as $child2) : ?>
            <li class="level1">
              <a href="<?php echo $child2['url'] ?>">
                <span><?php echo $child2['name'] ?></span>
              </a>
            </li>
            <?php endforeach ?>
          </ul>
        <?php endif ?>
      <?php $i++; endforeach ?>
    </ul>
  </div>
</div>
