<div class="quick-message-wrap">
	<div class="quick-message">
		<div class="qm-title">
			<h3>Quick Message Box</h3>
		</div>
		<div class="qm-input-area">
			<label for="contact">How to contact you:</label>
			<input type="text" name="contact" placeholder="phone or email"/>
			<textarea name="message" placeholder="If you have any questions or you want to leave a feedback, feel free to type it here."></textarea>
			<input type="submit" class="qm-send" value="send">
		</div>
	</div>
</div>