<div class="eyewear-rx-wrap">
	<div class="block-section-separator"></div>
	<div class="eyewear-rx">
		<div class="rx-left">
			<img src="<?php echo $this->getSkinUrl('images/rx-small.jpg') ?>">
		</div>
		<div class="rx-right">
			<div class="eyewear-rx-inner">
				<h3><?php echo $this->__('Prescription Sunglasses') ?></h3>
				<p><?php echo $this->__('Add a pair of your prescription lenses to your new sunglasses.') ?></p>
				<a class="light-btn" href="<?php echo $this->getUrl('prescription-sunglasses') ?>">Rx Sunglasses</a>
			</div>
		</div>
	</div>
	<div class="block-section-separator"></div>
</div>