<div class="eyewear-rx-wrap">
	<div class="block-section-separator"></div>
	<div class="eyewear-rx">
		<div class="rx-left">
			<img src="<?php echo $this->getSkinUrl('images/rx-small.jpg') ?>">
		</div>
		<div class="rx-right">
			<div class="eyewear-rx-inner">
				<h3>Prescription Sunglasses</h3>
				<p>Get your new sunglasses with a pair of prescription lenses.</p>
				<a class="white-btn" href="<?php echo $this->getUrl('men/prescription-sunglasses.html') ?>">Shop Men</a><a class="dark-btn" href="<?php echo $this->getUrl('women/prescription-sunglasses.html') ?>">Shop Women</a>
			</div>
		</div>
	</div>
	<div class="block-section-separator"></div>
</div>