
<div class="category-left-sort">
	<div class="category-leftfilter-header">
		<h3>Filter / Sort</h3>
	</div>
	<?php $i=0; foreach($this->sort_list as $sec) : ?>
		<?php $s_type = $sec['type'] ?>
		<?php $s_parent = isset($sec['parent']) ? $sec['parent'] : ''; ?>
		<?php $s_child = isset($sec['child']) ? $sec['child'] : ''; ?>
		<div class="sort-block<?php echo ' ' . $sec['code']; if ($s_parent) echo ' parent' ?><?php if ($s_child) echo ' child animated-hide' ?>" <?php if($s_type=='number') echo 'style="display:block"' ?> <?php if ($s_parent) echo 'data-child="' . $s_parent . '"' ?> <?php if ($s_child) echo 'data-parent="' . $s_child . '"' ?>>
			<h4 class="sort-block-title">
				<?php echo $sec['label'] ?>
			</h4>
			<div class="sort-block-opts" data-stype="<?php echo $s_type ?>">
				<?php if ($s_type == 'boolean') : ?>
					<input type="checkbox" name="<?php echo $sec['label'] ?>">
				<?php elseif ($s_type == 'number') : ?>
					<input type="range" name="<?php echo $sec['label'] ?>" min="<?php echo $sec['min'] ?>" max="<?php echo $sec['max'] ?>" value="<?php echo $sec['max'] ?>">
				<?php else : ?>
					<ul>
						<?php $j=0; foreach($sec['arr'] as $row) : ?>
							<?php $label = is_string($row) ? $row : $row['label']; ?>
							<?php $value = is_string($row) ? $row : $row['value']; ?>
							<?php if ($label || $value) : ?>
								<li>
									<div class="sort-btn<?php if ($s_child) echo ' child' ?>" <?php if($s_type=='color') echo 'style="background-color:' . $label .'" title="' . $label . '"'; elseif($s_type=='childstring') echo 'data-parent="' . $sec['parr'][$j] . '"' ?> data-value="<?php echo $value ?>" data-code="<?php echo $sec['code'] ?>"><?php if($s_type != 'color') echo $label ?></div>
								</li>
							<?php endif ?>
						<?php $j++; endforeach ?>
					</ul>
				<?php endif ?>
			</div>
			<hr class="sort-block-separator"/>
		</div>
	<?php $i++; endforeach ?>
</div>
