<div class="fs-shifter"></div>
<div class="fs-wrap">
	<div class="fs">

		<!-- left -->
		<div class="fs-left">
			<!-- filter block on/off -->
			<div class="fs-filters-switch">
				<span id="filters-switch">Filter</span>
			</div>

			<!-- filters reset button -->
			<div class="fs-filters-reset">
				<span id="filters-reset"><i class="fa fa-times"></i> reset filters</span>
			</div>
		</div>

		<!-- center -->
		<div class="fs-center">
			<ul class="fs-filters-ul"></ul>
		</div>

		<!-- right -->
		<div class="fs-right">
			<!-- category title -->
			<div class="fs-title-wrap">
				<span class="fs-title"></span>
			</div>

			<!-- sort wrap -->
			<div class="fs-sort">
				<span id="sort-switch">Sort<i class="fa fa-angle-down"></i></span>
			</div>
		</div>

	</div>
</div>
